server:
  port: 8085
spring:
  profiles:
    active: dev
  application:
    name: yunyi-portal
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/yunyi_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yunyi-port
  redis:
    host: 121.43.134.153 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: chxredis # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: /mall
#    username: yunyi
#    password: yunyi
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 自定义redis key
redis:
  database: yunyi
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        #feign客户端建立连接超时时间
        connect-timeout: 10000
        #feign客户端建立连接后读取资源超时时间
        read-timeout: 20000
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）

wx:
  app-id: wxfcdc76fbc6fa2ff9
  app-secret: 554091572f06ab927f61636840ace4a6
  #    app-id: wxd50a6186874267e6
  #    app-secret: 01748d234ec4bbaa42f33a07ba07907c
  mch-id: 111111
  mch-key: xxxxxx
  notify-url: http://www.example.com/wx/order/pay-notify
  # 商户证书文件路径
  # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
  key-path: xxxxx

alipay:
  appId: 2016110200787542
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQChnm/wudU1/0w6Pi8IRTrBJKR4Yrgz5PH5VptvsnQMO9kk7Df3NAd2u9sPiYFDUjDeRMgVwg9cBwqRC8yCDhKEyGv9MxqtsjyUKBsrFpKz9ls4ff4esgpiYEIATVqWhdBQus0B2H83M8nuDz+S1XiAlPRE9b2GKhjpgsSDuurfBEMd5kedsE3UJQozQg7LSGT9TKiwc0YxYY6OrN1qSvJK2IhwqY2KwwizCe7xS5wpxxUIqWyOz9jhHu8s2eUfkkoGb36vva7UoiZI7xVSsbRgyLJ9fiwBpR2vYLM3ESsmcHykTNhOwyrci/3cF9vr+bUlaFjymEEzkJcITNe8ONfpAgMBAAECggEABRFZwzugguPxePYQNXsuP3YtrhSyX/Yy3DWqBBOdbfDGe1Do5Fh+T2vOj6spIXpHTADuITiHkMQrwaaUEBPu4rkCIdtjX8Tx/1dOmshHa1szOw9AU6gTiUgpaacDSysBADcLTJ6ERq/aChvyS2FkOOvyyOLHwZg6VcAi91p6GOoViur5CpBYzlFN5BM3gHt8ajNREMstRfQHSSH+99buHUoWG7htqNQyd+Vv//Rqp5VJiiyYEMjl0hkjfoUhnjjCFNrVHVicJ7AV0a/nA0gHfWF3pWrRgipeytSGlozFIJNdZyvs24M2LXuraHr4OHFM5mlaqd992JDLHTbaFG758QKBgQDNO/gGOG/LtmUaoSHvm/UUBl86YkqsZduBjlVBZDdIwaSCYwRVn+Jp1OOSWxx8eEf/RZNgtHoqzanXhpbSaW6RgN1u+q1WjGDuwpC5E3hUYtmtuNIkrDBrvc5Qxm8GnnJZfXXSybP5/PHo4FQFWj6xUsmY2EeuLfz8fOgADm/H3QKBgQDJmJ3pAWtwt7Wx2/wMSXzP8dp2Y44e0vXjf39WCJS6E7Ro/UJiPZzQr5IhnTuhQCQhah+b0D+t87IvPIuO3jSgB2M5qqJIjH3SRj9g9TjH1fNgGHPa3OITlbiToyp3lEOnAkx9zc1UakWiW0Qv1m48CqWXtmML2gVBWTHa4dm1fQKBgGNyR4BcIG/Jdbwtj9AW9e46GDKmJiDbSj3AxjblZJRwoFI9wH/s9Tzq10q3s1nsvpZHFF6rlPbgqQeyQ6q5Q8ZlduaruQpTAzUuOgo0EP5y15+CCvGSLfRHCI3DWVEPvcD3NfxpmDfuBRoeeRgO3on135GcWz9fMVL3A0Pjuu5RAoGAE2tRIsXRPK1lojlnoSNfE4Tfn3HdmdiGeSCp+nafJQGK6mYjA+Wdeni/Id/Mg67zDAj1/INl7vK/ok85vkxnU1cC1uY59bUa1auQpV1Z194jMImKd3W5jVtpyUb5a0Vr8uWEysWNVulZxdb2zYjhW4VHCEM4bUbWJMJbzBLfbt0CgYBZil0jJj4/LQHKgvaVQ3lwzviEBXGD4ut52YH8cltp2YJFrfyfSnia68l5SKYit9WvY5+3dl7Q6WMaVVnTpzKXN7k+RuzNLnEa5fwZJclgxcBMPUpAQNDnVMTA9ERTlj36368Mh3Vpi1BCPbBXk2Wp52IAPF0WSRvOYpz/Zoyfzw==
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoZ5v8LnVNf9MOj4vCEU6wSSkeGK4M+Tx+Vabb7J0DDvZJOw39zQHdrvbD4mBQ1Iw3kTIFcIPXAcKkQvMgg4ShMhr/TMarbI8lCgbKxaSs/ZbOH3+HrIKYmBCAE1aloXQULrNAdh/NzPJ7g8/ktV4gJT0RPW9hioY6YLEg7rq3wRDHeZHnbBN1CUKM0IOy0hk/UyosHNGMWGOjqzdakryStiIcKmNisMIswnu8UucKccVCKlsjs/Y4R7vLNnlH5JKBm9+r72u1KImSO8VUrG0YMiyfX4sAaUdr2CzNxErJnB8pEzYTsMq3Iv93Bfb6/m1JWhY8phBM5CXCEzXvDjX6QIDAQAB
  #支付网关配置，这一项是写死的，正式环境是openapi.alipay.com
  gateway: openapi.alipaydev.com
  #支付成功之后的回调页面，只是一个友好页面。主要换成你自己映射的临时域名
  returnUrl: http://frnqxw.natappfree.cc/return.html
  #支付成功的接口回调，我们还没写，先空着
  notifyUrl:
