server:
  port: 9501
spring:
  profiles:
    active: dev
  application:
    name: yunyi-api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 121.43.134.153 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: chxredis # Redis服务器连接密码（默认为空）
management:
  endpoints:
    web:
      exposure:
        include: "*"