server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: yunyi-admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunyi_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 121.43.134.153 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: chxredis # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
redis:
  database: yunyi
  key:
    admin: 'ums:admin'
  expire:
    common: 86400 # 24小时
management:
  endpoints:
    web:
      exposure:
        include: "*"