server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: yunyi-admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/yunyi_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      #避免空闲时间过长超过最大空闲时间而被断开
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
#    password: chxredis # Redis服务器连接密码（默认为空）
    #timeout: 3000ms # 连接超时时间（毫秒）
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
redis:
  database: yunyi
  key:
    admin: 'ums:admin'
  expire:
    common: 86400 # 24小时
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tGENg3ULShaHqMnJ7fd # 访问身份验证中用到用户标识
    accessKeySecret: AhOABwiMBepDrsrbsuXmQs8lTJHXjx # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: yunyi-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://4628b9j619.zicp.vip/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: yunyi/images/ # 上传文件夹路径前缀
management:
  endpoints:
    web:
      exposure:
        include: "*"

pay:
  alibaba:
    appid: 2016110200787542
    charset: utf-8
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjnQndrmIrs2NWdduIu0NYkdcQaHutX9DQuXSz/TPIkbwl7AB0EqJcinUXsaaBejY6555AvWrZjMnD526XefQEVUQA2doDewQNQZvTNXs3aGdzCQQ6IYKwLR8I0V0LmnE+aK29jrYFTsSsFPuKI/HGuX9Reg30d7WMctZ14mOwHEKkdswRm4L8MmK5KBDhPzk6xQ1Gh3rvZtNAXkMJf19kxk72lr4ndQfB1g+249OqmrPfelezBZTPesTy5Y8bNGIJcyqlaDuQWQOlZY88qvAY4ll3HyELSO4ZAJAq9M6O9ZPm/Lh5fdudzzrpp4Po3jzfreUv0PFUy2M5cqgEb6cWQIDAQAB
    merchantPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQChnm/wudU1/0w6Pi8IRTrBJKR4Yrgz5PH5VptvsnQMO9kk7Df3NAd2u9sPiYFDUjDeRMgVwg9cBwqRC8yCDhKEyGv9MxqtsjyUKBsrFpKz9ls4ff4esgpiYEIATVqWhdBQus0B2H83M8nuDz+S1XiAlPRE9b2GKhjpgsSDuurfBEMd5kedsE3UJQozQg7LSGT9TKiwc0YxYY6OrN1qSvJK2IhwqY2KwwizCe7xS5wpxxUIqWyOz9jhHu8s2eUfkkoGb36vva7UoiZI7xVSsbRgyLJ9fiwBpR2vYLM3ESsmcHykTNhOwyrci/3cF9vr+bUlaFjymEEzkJcITNe8ONfpAgMBAAECggEABRFZwzugguPxePYQNXsuP3YtrhSyX/Yy3DWqBBOdbfDGe1Do5Fh+T2vOj6spIXpHTADuITiHkMQrwaaUEBPu4rkCIdtjX8Tx/1dOmshHa1szOw9AU6gTiUgpaacDSysBADcLTJ6ERq/aChvyS2FkOOvyyOLHwZg6VcAi91p6GOoViur5CpBYzlFN5BM3gHt8ajNREMstRfQHSSH+99buHUoWG7htqNQyd+Vv//Rqp5VJiiyYEMjl0hkjfoUhnjjCFNrVHVicJ7AV0a/nA0gHfWF3pWrRgipeytSGlozFIJNdZyvs24M2LXuraHr4OHFM5mlaqd992JDLHTbaFG758QKBgQDNO/gGOG/LtmUaoSHvm/UUBl86YkqsZduBjlVBZDdIwaSCYwRVn+Jp1OOSWxx8eEf/RZNgtHoqzanXhpbSaW6RgN1u+q1WjGDuwpC5E3hUYtmtuNIkrDBrvc5Qxm8GnnJZfXXSybP5/PHo4FQFWj6xUsmY2EeuLfz8fOgADm/H3QKBgQDJmJ3pAWtwt7Wx2/wMSXzP8dp2Y44e0vXjf39WCJS6E7Ro/UJiPZzQr5IhnTuhQCQhah+b0D+t87IvPIuO3jSgB2M5qqJIjH3SRj9g9TjH1fNgGHPa3OITlbiToyp3lEOnAkx9zc1UakWiW0Qv1m48CqWXtmML2gVBWTHa4dm1fQKBgGNyR4BcIG/Jdbwtj9AW9e46GDKmJiDbSj3AxjblZJRwoFI9wH/s9Tzq10q3s1nsvpZHFF6rlPbgqQeyQ6q5Q8ZlduaruQpTAzUuOgo0EP5y15+CCvGSLfRHCI3DWVEPvcD3NfxpmDfuBRoeeRgO3on135GcWz9fMVL3A0Pjuu5RAoGAE2tRIsXRPK1lojlnoSNfE4Tfn3HdmdiGeSCp+nafJQGK6mYjA+Wdeni/Id/Mg67zDAj1/INl7vK/ok85vkxnU1cC1uY59bUa1auQpV1Z194jMImKd3W5jVtpyUb5a0Vr8uWEysWNVulZxdb2zYjhW4VHCEM4bUbWJMJbzBLfbt0CgYBZil0jJj4/LQHKgvaVQ3lwzviEBXGD4ut52YH8cltp2YJFrfyfSnia68l5SKYit9WvY5+3dl7Q6WMaVVnTpzKXN7k+RuzNLnEa5fwZJclgxcBMPUpAQNDnVMTA9ERTlj36368Mh3Vpi1BCPbBXk2Wp52IAPF0WSRvOYpz/Zoyfzw==
    notifyUrl: http://4628b9j619.zicp.vip/yunyi-admin/order/refundNotify
    returnUrl:
    signType: RSA2
    timeout: 30m

#通知相关配置
notify:
  mail:
    # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
    enable: true
    #      host: smtp.exmail.qq.com
    host: smtp.qq.com
    username: 2948938288@qq.com
    password: cmqsqehqermbdeie
    sendfrom: 2948938288@qq.com
    sendto: 1369185461@qq.com
    port: 465
  # 短消息模版通知配置
  # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
  sms:
    enable: true
    # 如果是腾讯云短信，则设置active的值tencent
    # 如果是阿里云短信，则设置active的值aliyun
    active: tencent
    sign: 肥猫腿急送
    template:
      - name: paySucceed
        templateId: 1297320
      - name: captcha
        templateId: 1297393
      - name: ship
        templateId: 1297396
      - name: refund
        templateId: 1297391
    tencent:
      appid: 1400502378
      appkey: b1b10cb79883fdbd8d3919659b8905df
    aliyun:
      regionId: xxx
      accessKeyId: xxx
      accessKeySecret: xxx
