server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: yunyi-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes: #配置路由规则
        - id: yunyi-api-route
          uri: lb://yunyi-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: yunyi-auth-route
          uri: lb://yunyi-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    host: 121.43.134.153 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: chxredis # Redis服务器连接密码（默认为空）
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/test/hello"
      - "/api/hello"